services:
  - type: web
    name: AUTOMATIC1111
    env: python
    region: Oregon
    plan: free
    buildCommand: "./webui.sh "
    startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
    envVars:
    - key: PYTHON_VERSION
      value: 3.10.6
